from pathlib import Path

from bot.handlers.state_constants import (
    ADDING_ECO_TASK,
    ADDING_VOLUNTEER,
    ADDRESS_INPUT,
    END,
    SPECIFY_ACTIVITY_RADIUS,
    SPECIFY_CAR_AVAILABILITY,
    SPECIFY_PHONE_PERMISSION,
)

BASE_PATTERN = "^({command})$"

REPORT_SOCIAL_PROBLEM_CMD = BASE_PATTERN.format(command="Сообщить о социальной проблеме")
REPORT_ECO_PROBLEM_CMD = BASE_PATTERN.format(command=ADDING_ECO_TASK)
BECOME_VOLUNTEER_CMD = BASE_PATTERN.format(command=ADDING_VOLUNTEER)
END_CMD = BASE_PATTERN.format(command=END)

SPECIFY_ADDRESS_CMD = BASE_PATTERN.format(command=ADDRESS_INPUT)
SPECIFY_ACTIVITY_RADIUS_CMD = BASE_PATTERN.format(command=SPECIFY_ACTIVITY_RADIUS)
SPECIFY_CAR_AVAILABILITY_CMD = BASE_PATTERN.format(command=SPECIFY_CAR_AVAILABILITY)
SPECIFY_PHONE_PERMISSION_CMD = BASE_PATTERN.format(command=SPECIFY_PHONE_PERMISSION)

BASE_DIR = Path(__file__).resolve().parent.parent
DATA_PATH = BASE_DIR.parent / "persistence_data" / "bot_persistence_data"
SAVE_PERSISTENCE_INTERVAL = 30

# FOR IMAGE_RESIZER
MAXIMUM_SIZE_OF_IMAGE_KB = 300
TARGET_WIDTH = 1000
QUALITY = 95
KB_IN_MB = 1024
