"""Removed unique parameter from volunteers phone field

Revision ID: 379e9adafdd5
Revises: 345200deafa6
Create Date: 2023-03-31 14:29:15.071090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '379e9adafdd5'
down_revision = '345200deafa6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('volunteer', schema=None) as batch_op:
        batch_op.drop_constraint('volunteer_phone_key', type_='unique')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('volunteer', schema=None) as batch_op:
        batch_op.create_unique_constraint('volunteer_phone_key', ['phone'])

    # ### end Alembic commands ###
