"""add_username_field_to_user_model

Revision ID: 592f9f446d40
Revises: 77eb86285a9e
Create Date: 2023-02-10 17:05:07.131461

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "592f9f446d40"
down_revision = "77eb86285a9e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(sa.Column("telegram_username", sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("telegram_username")

    # ### end Alembic commands ###
