"""Add tables Pollution Assistance_disabled

Revision ID: 6b88f42d644c
Revises: 2f387fd648c6
Create Date: 2023-01-09 19:52:44.818606

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "6b88f42d644c"
down_revision = "2f387fd648c6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "assistance_disabled",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("city", sa.Text(), nullable=False),
        sa.Column("street", sa.Text(), nullable=False),
        sa.Column("house", sa.Text(), nullable=False),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("volunteer_id", sa.Integer(), nullable=True),
        sa.Column("users_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["users_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["volunteer_id"],
            ["volunteer.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "pollution",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("latitude", sa.Text(), nullable=False),
        sa.Column("longitude", sa.Text(), nullable=False),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("volunteer_id", sa.Integer(), nullable=True),
        sa.Column("users_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["users_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["volunteer_id"],
            ["volunteer.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("pollution")
    op.drop_table("assistance_disabled")
    # ### end Alembic commands ###
