"""you_migration_name

Revision ID: a277a177c4b1
Revises: 592f9f446d40
Create Date: 2023-02-13 16:13:46.626382

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "a277a177c4b1"
down_revision = "592f9f446d40"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
