"""add telegramm-id field

Revision ID: b26f57973f92
Revises: 6b88f42d644c
Create Date: 2023-01-10 20:28:24.213483

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "b26f57973f92"
down_revision = "6b88f42d644c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("assistance_disabled", schema=None) as batch_op:
        batch_op.add_column(sa.Column("telegram_id", sa.Integer(), nullable=True))

    with op.batch_alter_table("pollution", schema=None) as batch_op:
        batch_op.add_column(sa.Column("telegram_id", sa.Integer(), nullable=True))

    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.alter_column("telegram_id", existing_type=sa.VARCHAR(length=64), nullable=True)
        batch_op.drop_index("ix_user_telegram_id")

    with op.batch_alter_table("volunteer", schema=None) as batch_op:
        batch_op.add_column(sa.Column("telegram_id", sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("volunteer", schema=None) as batch_op:
        batch_op.drop_column("telegram_id")

    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.create_index("ix_user_telegram_id", ["telegram_id"], unique=False)
        batch_op.alter_column("telegram_id", existing_type=sa.VARCHAR(length=64), nullable=False)

    with op.batch_alter_table("pollution", schema=None) as batch_op:
        batch_op.drop_column("telegram_id")

    with op.batch_alter_table("assistance_disabled", schema=None) as batch_op:
        batch_op.drop_column("telegram_id")

    # ### end Alembic commands ###
