"""add tags

Revision ID: b5707fc337c1
Revises: 379e9adafdd5
Create Date: 2023-05-13 13:21:10.556750

"""
import sqlalchemy as sa
from geoalchemy2 import Geography
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = 'b5707fc337c1'
down_revision = '379e9adafdd5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag_assistance',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('name', sa.String(length=35), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tag_pollution',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('name', sa.String(length=35), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assistance_disabled', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tag_id', postgresql.UUID(as_uuid=True), nullable=True))
        batch_op.create_foreign_key(None, 'tag_assistance', ['tag_id'], ['id'])

    with op.batch_alter_table('pollution', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tag_id', postgresql.UUID(as_uuid=True), nullable=True))
        batch_op.create_foreign_key(None, 'tag_pollution', ['tag_id'], ['id'])

    

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    with op.batch_alter_table('pollution', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('tag_id')

    with op.batch_alter_table('assistance_disabled', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('tag_id')

    op.drop_table('tag_pollution')
    op.drop_table('tag_assistance')
    # ### end Alembic commands ###
