"""add volunteer holiday

Revision ID: da5fb4d5fc69
Revises: 379e9adafdd5
Create Date: 2023-05-14 19:47:43.264128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da5fb4d5fc69'
down_revision = '379e9adafdd5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('volunteer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('holiday_start', sa.TIMESTAMP(), nullable=True))
        batch_op.add_column(sa.Column('holiday_end', sa.TIMESTAMP(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('volunteer', schema=None) as batch_op:
        batch_op.drop_column('holiday_end')
        batch_op.drop_column('holiday_start')

    # ### end Alembic commands ###
