"""add holiday and in_active to Volunteer

Revision ID: f2dfee9a709b
Revises: 379e9adafdd5
Create Date: 2023-05-17 07:55:28.161857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2dfee9a709b'
down_revision = '379e9adafdd5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('volunteer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('holiday_start', sa.TIMESTAMP(), nullable=True))
        batch_op.add_column(sa.Column('holiday_end', sa.TIMESTAMP(), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('volunteer', schema=None) as batch_op:
        batch_op.drop_column('is_active')
        batch_op.drop_column('holiday_end')
        batch_op.drop_column('holiday_start')

    # ### end Alembic commands ###
